services:
  envoy-vrp:
    image: envoyproxy/envoy-google-vrp-dev:latest
    platform: linux/amd64
    environment:
      ENVOY_EDGE_EXTRA_ARGS: "--log-level info"
      ENVOY_ORIGIN_EXTRA_ARGS: "--log-level info"
    container_name: zerodaycloud-envoy
    ports:
      - "10000:10000"
    mem_limit: 3g
    restart: unless-stopped
