services:
  fluentbit:
    image: fluent/fluent-bit:latest
    container_name: zerodaycloud-fluentbit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    ports:
      - "9880:9880"
      - "2020:2020"
    restart: unless-stopped
