model_list:
  - model_name: zdc-mock
    litellm_params:
      model: openai/zdc-mock
      api_base: http://mock-openai:8080/v1
      api_key: os.environ/MOCK_OPENAI_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
