Listen 443

SSLSessionCache "shmcb:/usr/local/apache2/logs/ssl_scache(512000)"

<VirtualHost *:443>
    ServerName localhost
    DocumentRoot "/usr/local/apache2/htdocs"
    SSLEngine on
    SSLCertificateFile "/usr/local/apache2/conf/certs/apache.crt"
    SSLCertificateKeyFile "/usr/local/apache2/conf/certs/apache.key"
</VirtualHost>
