services:
  mariadb:
    image: mariadb:latest
    container_name: zerodaycloud-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: zerodaycloud1!
      MARIADB_DATABASE: demo
      MARIADB_USER: demo
      MARIADB_PASSWORD: zerodaycloud1!
    command: ["--local-infile=0"]
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 30
    restart: unless-stopped
